import type { AuditFindings, Issue, CoreWebVitals } from '../types/index.js';

/**
 * Escape pipe characters and newlines in Markdown table cells.
 */
function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ').replace(/\r/g, '');
}

function severityEmoji(severity: Issue['severity']): string {
  switch (severity) {
    case 'critical': return '🔴 Critical';
    case 'warning': return '🟡 Warning';
    case 'info': return '🔵 Info';
  }
}

/**
 * Format the PR title for an audit run.
 * Example: "SEO Audit: acme-website — 2024-01-15 (3 critical issues)"
 */
export function formatPRTitle(findings: AuditFindings): string {
  const criticalCount = findings.issues.filter(i => i.severity === 'critical').length;
  const suffix = criticalCount > 0 ? ` (${criticalCount} critical issue${criticalCount === 1 ? '' : 's'})` : '';
  return `SEO Audit: ${findings.siteId} — ${findings.auditDate}${suffix}`;
}

/**
 * Format the full PR body as GitHub-flavored Markdown.
 * Structure:
 *   ## Executive Summary
 *   | metric | value |
 *   ## Critical Issues (if any)
 *   ## All Findings
 *   | Page URL | Issue | Severity | Description |
 *   ## Core Web Vitals (if available)
 */
export function formatPRBody(findings: AuditFindings): string {
  const { siteId, auditDate, pagesAudited, issues, coreWebVitals } = findings;

  const criticalCount = issues.filter(i => i.severity === 'critical').length;
  const warningCount = issues.filter(i => i.severity === 'warning').length;
  const infoCount = issues.filter(i => i.severity === 'info').length;
  const totalCount = issues.length;

  const statusBadge = criticalCount > 0 ? '**Status: NEEDS ATTENTION**' : '**Status: PASS** (no critical issues)';

  const sections: string[] = [];

  // ─── Executive Summary ───────────────────────────────────────────────────
  sections.push(`## Executive Summary

${statusBadge}

| Metric | Value |
|--------|-------|
| Site | \`${siteId}\` |
| Audit Date | ${auditDate} |
| Pages Audited | ${pagesAudited} |
| Total Issues | ${totalCount} |
| 🔴 Critical | ${criticalCount} |
| 🟡 Warning | ${warningCount} |
| 🔵 Info | ${infoCount} |`);

  // ─── Critical Issues (if any) ────────────────────────────────────────────
  const criticalIssues = issues.filter(i => i.severity === 'critical');
  if (criticalIssues.length > 0) {
    const rows = criticalIssues.map(issue => {
      const pageDisplay = escapeTableCell(issue.pageUrl);
      const ruleDisplay = escapeTableCell(issue.rule);
      const descDisplay = escapeTableCell(issue.description);
      return `| ${pageDisplay} | ${ruleDisplay} | ${descDisplay} |`;
    }).join('\n');

    sections.push(`## 🔴 Critical Issues

| Page URL | Rule | Description |
|----------|------|-------------|
${rows}`);
  }

  // ─── All Findings ────────────────────────────────────────────────────────
  if (issues.length === 0) {
    sections.push(`## All Findings

No issues detected. Great work!`);
  } else {
    // Sort: critical first, then warning, then info
    const sorted = [...issues].sort((a, b) => {
      const order = { critical: 0, warning: 1, info: 2 } as const;
      return order[a.severity] - order[b.severity];
    });

    const rows = sorted.map(issue => {
      const pageDisplay = escapeTableCell(issue.pageUrl);
      const ruleDisplay = escapeTableCell(issue.rule);
      const sevDisplay = severityEmoji(issue.severity);
      const descDisplay = escapeTableCell(issue.description);
      return `| ${pageDisplay} | ${ruleDisplay} | ${sevDisplay} | ${descDisplay} |`;
    }).join('\n');

    sections.push(`## All Findings

| Page URL | Rule | Severity | Description |
|----------|------|----------|-------------|
${rows}`);
  }

  // ─── Core Web Vitals ─────────────────────────────────────────────────────
  if (coreWebVitals) {
    sections.push(formatCoreWebVitalsSection(coreWebVitals));
  }

  // ─── Footer ──────────────────────────────────────────────────────────────
  sections.push(`---
*Generated by SEO Agent on ${auditDate}. Review findings and merge when addressed.*`);

  return sections.join('\n\n');
}

function formatCoreWebVitalsSection(vitals: CoreWebVitals): string {
  function fmt(val: number | null, unit: string = 'ms'): string {
    return val !== null ? `${val}${unit}` : 'N/A';
  }

  const scoreLabel = vitals.performanceScore !== null
    ? vitals.performanceScore >= 90 ? '🟢 Good'
      : vitals.performanceScore >= 50 ? '🟡 Needs Improvement'
      : '🔴 Poor'
    : 'N/A';

  return `## Core Web Vitals

| Metric | Value | Source |
|--------|-------|--------|
| Performance Score | ${scoreLabel} (${vitals.performanceScore ?? 'N/A'}/100) | PageSpeed Insights |
| LCP (Largest Contentful Paint) | ${fmt(vitals.lcp)} | PageSpeed Insights |
| FID (First Input Delay) | ${fmt(vitals.fid)} | PageSpeed Insights |
| CLS (Cumulative Layout Shift) | ${fmt(vitals.cls, '')} | PageSpeed Insights |
| FCP (First Contentful Paint) | ${fmt(vitals.fcp)} | PageSpeed Insights |
| TTFB (Time to First Byte) | ${fmt(vitals.ttfb)} | PageSpeed Insights |`;
}
