import type { AuditFindings, Issue, CoreWebVitals, FixCategory, RiskCategory, FixResult, FixPRTracking } from '../types/index.js';

/**
 * Escape pipe characters and newlines in Markdown table cells.
 */
function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ').replace(/\r/g, '');
}

function severityEmoji(severity: Issue['severity']): string {
  switch (severity) {
    case 'critical': return '🔴 Critical';
    case 'warning': return '🟡 Warning';
    case 'info': return '🔵 Info';
  }
}

/**
 * Format the PR title for an audit run.
 * Example: "SEO Audit: acme-website — 2024-01-15 (3 critical issues)"
 */
export function formatPRTitle(findings: AuditFindings): string {
  const criticalCount = findings.issues.filter(i => i.severity === 'critical').length;
  const suffix = criticalCount > 0 ? ` (${criticalCount} critical issue${criticalCount === 1 ? '' : 's'})` : '';
  return `SEO Audit: ${findings.siteId} — ${findings.auditDate}${suffix}`;
}

/**
 * Format the full PR body as GitHub-flavored Markdown.
 * Structure:
 *   ## Executive Summary
 *   | metric | value |
 *   ## Critical Issues (if any)
 *   ## All Findings
 *   | Page URL | Issue | Severity | Description |
 *   ## Core Web Vitals (if available)
 */
export function formatPRBody(findings: AuditFindings): string {
  const { siteId, auditDate, pagesAudited, issues, coreWebVitals } = findings;

  const criticalCount = issues.filter(i => i.severity === 'critical').length;
  const warningCount = issues.filter(i => i.severity === 'warning').length;
  const infoCount = issues.filter(i => i.severity === 'info').length;
  const totalCount = issues.length;

  const statusBadge = criticalCount > 0 ? '**Status: NEEDS ATTENTION**' : '**Status: PASS** (no critical issues)';

  const sections: string[] = [];

  // ─── Executive Summary ───────────────────────────────────────────────────
  sections.push(`## Executive Summary

${statusBadge}

| Metric | Value |
|--------|-------|
| Site | \`${siteId}\` |
| Audit Date | ${auditDate} |
| Pages Audited | ${pagesAudited} |
| Total Issues | ${totalCount} |
| 🔴 Critical | ${criticalCount} |
| 🟡 Warning | ${warningCount} |
| 🔵 Info | ${infoCount} |`);

  // ─── Critical Issues (if any) ────────────────────────────────────────────
  const criticalIssues = issues.filter(i => i.severity === 'critical');
  if (criticalIssues.length > 0) {
    const rows = criticalIssues.map(issue => {
      const pageDisplay = escapeTableCell(issue.pageUrl);
      const ruleDisplay = escapeTableCell(issue.rule);
      const descDisplay = escapeTableCell(issue.description);
      return `| ${pageDisplay} | ${ruleDisplay} | ${descDisplay} |`;
    }).join('\n');

    sections.push(`## 🔴 Critical Issues

| Page URL | Rule | Description |
|----------|------|-------------|
${rows}`);
  }

  // ─── All Findings ────────────────────────────────────────────────────────
  if (issues.length === 0) {
    sections.push(`## All Findings

No issues detected. Great work!`);
  } else {
    // Sort: critical first, then warning, then info
    const sorted = [...issues].sort((a, b) => {
      const order = { critical: 0, warning: 1, info: 2 } as const;
      return order[a.severity] - order[b.severity];
    });

    const rows = sorted.map(issue => {
      const pageDisplay = escapeTableCell(issue.pageUrl);
      const ruleDisplay = escapeTableCell(issue.rule);
      const sevDisplay = severityEmoji(issue.severity);
      const descDisplay = escapeTableCell(issue.description);
      return `| ${pageDisplay} | ${ruleDisplay} | ${sevDisplay} | ${descDisplay} |`;
    }).join('\n');

    sections.push(`## All Findings

| Page URL | Rule | Severity | Description |
|----------|------|----------|-------------|
${rows}`);
  }

  // ─── Core Web Vitals ─────────────────────────────────────────────────────
  if (coreWebVitals) {
    sections.push(formatCoreWebVitalsSection(coreWebVitals));
  }

  // ─── Footer ──────────────────────────────────────────────────────────────
  sections.push(`---
*Generated by SEO Agent on ${auditDate}. Review findings and merge when addressed.*`);

  return sections.join('\n\n');
}

function formatCoreWebVitalsSection(vitals: CoreWebVitals): string {
  function fmt(val: number | null, unit: string = 'ms'): string {
    return val !== null ? `${val}${unit}` : 'N/A';
  }

  const scoreLabel = vitals.performanceScore !== null
    ? vitals.performanceScore >= 90 ? '🟢 Good'
      : vitals.performanceScore >= 50 ? '🟡 Needs Improvement'
      : '🔴 Poor'
    : 'N/A';

  return `## Core Web Vitals

| Metric | Value | Source |
|--------|-------|--------|
| Performance Score | ${scoreLabel} (${vitals.performanceScore ?? 'N/A'}/100) | PageSpeed Insights |
| LCP (Largest Contentful Paint) | ${fmt(vitals.lcp)} | PageSpeed Insights |
| FID (First Input Delay) | ${fmt(vitals.fid)} | PageSpeed Insights |
| CLS (Cumulative Layout Shift) | ${fmt(vitals.cls, '')} | PageSpeed Insights |
| FCP (First Contentful Paint) | ${fmt(vitals.fcp)} | PageSpeed Insights |
| TTFB (Time to First Byte) | ${fmt(vitals.ttfb)} | PageSpeed Insights |`;
}

// ─── Phase 2: Fix PR formatters ───────────────────────────────────────────────

const FIX_CATEGORY_DESCRIPTIONS: Record<FixCategory, string> = {
  'title-tag': 'Title tags appear as the clickable headline in search results and directly affect click-through rate (CTR). Missing or duplicate title tags reduce organic visibility.',
  'meta-description': 'Meta descriptions are shown as preview text in search results. They influence CTR and provide context to both users and search engines.',
  'og-tags': 'Open Graph tags control how pages appear when shared on social media. Missing tags result in unappealing auto-generated previews that reduce social traffic.',
  'alt-text': 'Image alt attributes improve accessibility (WCAG compliance) and give search engines context for image content, contributing to image search ranking.',
  'heading-hierarchy': 'Proper H1-H6 heading structure helps search engines understand page content hierarchy and improves accessibility for screen readers.',
  'schema-markup': 'Schema.org JSON-LD markup enables rich results in Google Search (star ratings, breadcrumbs, FAQs), increasing search result click-through rates.',
};

/**
 * Format the PR title for a fix run.
 * Example: "SEO Fix [meta-description]: acme-website — 2026-03-21"
 */
export function formatFixPRTitle(category: FixCategory, date: string, siteId: string): string {
  return `SEO Fix [${category}]: ${siteId} — ${date}`;
}

/**
 * Format the full PR body for a fix PR.
 * Includes: what was fixed, why, changes table, build validation status, discovery backlink.
 */
export function formatFixPRBody(fixResults: FixResult[], auditPRNumber?: number): string {
  const sections: string[] = [];

  // ── What Was Fixed ────────────────────────────────────────────────────────
  const categoryCounts = new Map<FixCategory, number>();
  for (const r of fixResults) {
    const count = categoryCounts.get(r.fix.category) ?? 0;
    categoryCounts.set(r.fix.category, count + 1);
  }

  const whatFixed = Array.from(categoryCounts.entries())
    .map(([cat, count]) => `- **${cat}**: ${count} file${count === 1 ? '' : 's'} fixed`)
    .join('\n');

  sections.push(`## What Was Fixed\n\n${whatFixed}`);

  // ── Why This Was Applied ──────────────────────────────────────────────────
  const categories = Array.from(new Set(fixResults.map(r => r.fix.category)));
  const whyLines = categories
    .map(cat => `**${cat}:** ${FIX_CATEGORY_DESCRIPTIONS[cat]}`)
    .join('\n\n');

  sections.push(`## Why This Was Applied\n\n${whyLines}`);

  // ── Changes Made ──────────────────────────────────────────────────────────
  const rows = fixResults.map(r => {
    const file = escapeTableCell(r.fix.sourceFile);
    const issueCount = r.fix.issueIds.length;
    const buildStatus = r.buildPassed ? '✓ Passed' : '✗ Failed';
    return `| ${file} | ${issueCount} | ${buildStatus} |`;
  });

  sections.push(`## Changes Made\n\n| File | Issues Fixed | Build Status |\n|------|-------------|-------------|\n${rows.join('\n')}`);

  // ── Build Validation ──────────────────────────────────────────────────────
  const allPassed = fixResults.every(r => r.buildPassed);
  const failedBuilds = fixResults.filter(r => !r.buildPassed);

  if (allPassed) {
    sections.push(`## Build Validation\n\n✓ All changes passed \`next build\` validation.`);
  } else {
    const errorDetails = failedBuilds
      .map(r => `**${r.fix.sourceFile}:** ${r.buildError ?? 'Unknown error'}`)
      .join('\n\n');
    sections.push(`## Build Validation\n\n⚠️ **Build failed on ${failedBuilds.length} file${failedBuilds.length === 1 ? '' : 's'}** — this PR is labeled \`needs-review\`. Please inspect the changes before merging.\n\n${errorDetails}`);
  }

  // ── Discovery ─────────────────────────────────────────────────────────────
  const discovery = auditPRNumber != null
    ? `Discovered by audit PR #${auditPRNumber}`
    : 'Run manually';

  sections.push(`## Discovery\n\n${discovery}`);

  // ── Footer ────────────────────────────────────────────────────────────────
  sections.push(`---\n*Generated by SEO Agent. Review changes and merge when satisfied.*`);

  return sections.join('\n\n');
}

/**
 * Get GitHub label names for a fix PR.
 * - 'seo-auto-fix': always applied
 * - 'needs-review': applied if risk is needs-review OR any fix failed build
 * - 'first-run': applied if submittedCount < firstRunLimit (trust establishment period)
 */
export function getFixPRLabels(
  riskCategory: RiskCategory,
  fixPRTracking: FixPRTracking,
  fixResults: FixResult[] = [],
): string[] {
  const labels: string[] = ['seo-auto-fix'];

  const buildFailed = fixResults.some(r => !r.buildPassed);
  if (riskCategory === 'needs-review' || buildFailed) {
    labels.push('needs-review');
  }

  if (fixPRTracking.submittedCount < fixPRTracking.firstRunLimit) {
    labels.push('first-run');
  }

  return labels;
}
